plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.parcelize)
}

android {
    namespace = 'com.cappielloantonio.tempo'
    //noinspection GradleDependency
    compileSdk = 36
    buildToolsVersion = '36.0.0'

    defaultConfig {
        minSdkVersion 24
        //noinspection OldTargetApi
        targetSdk = 36

        versionCode 42
        versionName '4.24.0'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'

        javaCompileOptions {
            annotationProcessorOptions {
                arguments += [
                        "room.schemaLocation": "$projectDir/schemas".toString(),
                        "room.incremental"   : "true"
                ]
            }
        }

        externalNativeBuild {
            cmake {
                cppFlags '-std=c++17'
                abiFilters 'arm64-v8a'
            }
        }
    }

    ndkVersion = '28.0.12674087'

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }

    splits {
        abi {
            enable = true
            reset()
            include 'arm64-v8a', 'armeabi-v7a', 'x86_64'
            //noinspection ChromeOsAbiSupport
            universalApk = true
        }
    }

    dependenciesInfo {
        // Disables dependency metadata when building APKs (for IzzyOnDroid/F-Droid)
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles (for Google Play)
        includeInBundle = false
    }

    flavorDimensions += "default"

    productFlavors {
        tempus {
            dimension = "default"
            applicationId = 'com.eddyizm.tempus'
        }

        degoogled {
            dimension = "default"
            applicationId = "com.eddyizm.degoogled.tempus"
        }
    }

    buildTypes {
        release {
            shrinkResources = true
            minifyEnabled = true
            debuggable = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        debug {
            applicationIdSuffix = ".debug"
            debuggable = true
        }
    }

    buildFeatures {
        viewBinding = true
        buildConfig = true
    }
}

dependencies {
    implementation files('../libs/lib-decoder-ffmpeg-release.aar')

    // AndroidX
    implementation libs.androidx.activity
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.coordinatorlayout
    implementation libs.androidx.preference.ktx
    implementation libs.androidx.navigation.fragment.ktx
    implementation libs.androidx.navigation.ui.ktx
    implementation libs.androidx.recyclerview
    implementation libs.androidx.room.runtime
    implementation libs.androidx.splashscreen
    implementation libs.androidx.appcompat
    implementation libs.androidx.swiperefreshlayout

    // Android Material
    implementation libs.material

    // Glide
    implementation libs.glide
    implementation libs.glide.annotations
    annotationProcessor libs.glide.compiler

    // Media3
    implementation libs.media3.session
    implementation libs.media3.common
    implementation libs.media3.exoplayer
    implementation libs.media3.ui
    implementation libs.media3.exoplayer.hls
    tempusImplementation libs.media3.cast

    // Room Compiler
    annotationProcessor libs.androidx.room.compiler

    // Retrofit
    implementation libs.retrofit
    implementation libs.retrofit.converter.gson
    implementation libs.okhttp.logging

    // Misc
    implementation libs.sdp.android
    implementation libs.customactivityoncrash
    implementation(libs.shimmer) {
        artifact {
            name = 'shimmer'
            type = 'aar'
        }
    }
    implementation libs.kotlin.metadata

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.mockito:mockito-core:5.12.0'
    testImplementation 'org.mockito.kotlin:mockito-kotlin:5.4.0'
    testImplementation 'androidx.arch.core:core-testing:2.2.0'

    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.androidx.test.runner
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}