name: Github Release Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.ref_name, '-dev') }}
    permissions:
      contents: write
    steps:
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Cache Gradle and wrapper
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build All Release APKs
        id: build
        run: |
          sed -ri '/org.gradle.toolchains.foojay-resolver-convention/d' settings.gradle
          bash ./gradlew assembleTempusRelease
          bash ./gradlew assembleDegoogledRelease

      - name: Sign Tempus Release APKs
        id: sign_tempus_release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/tempus/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS_GITHUB }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD_GITHUB }}
        env:
          BUILD_TOOLS_VERSION: "36.0.0"

      - name: Sign Degoogled Release APKs
        id: sign_degoogled_release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/degoogled/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS_GITHUB }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD_GITHUB }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Rename Signed APKs to match local pattern
        run: |
          # Rename Tempus signed APKs
          for file in app/build/outputs/apk/tempus/release/*-signed.apk; do
            new_name=$(echo "$file" | sed 's/-unsigned-signed\.apk$/.apk/' | sed 's/-signed\.apk$/.apk/')
            mv "$file" "$new_name"
          done

          # Rename Degoogled signed APKs
          for file in app/build/outputs/apk/degoogled/release/*-signed.apk; do
            new_name=$(echo "$file" | sed 's/-unsigned-signed\.apk$/.apk/' | sed 's/-signed\.apk$/.apk/')
            mv "$file" "$new_name"
          done

      - name: Rename Mapping Files
        run: |
          mv -v app/build/outputs/mapping/tempusRelease/mapping.txt app/build/outputs/mapping/tempusRelease/mapping_Tempus.txt
          mv -v app/build/outputs/mapping/degoogledRelease/mapping.txt app/build/outputs/mapping/degoogledRelease/mapping_Degoogled.txt

      - name: Compress Mapping Files
        run: |
          gzip -v app/build/outputs/mapping/tempusRelease/mapping_Tempus.txt
          gzip -v app/build/outputs/mapping/degoogledRelease/mapping_Degoogled.txt

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          draft: true
          prerelease: false
          files: |
            app/build/outputs/apk/tempus/release/*-release.apk
            app/build/outputs/apk/degoogled/release/*-release.apk
            app/build/outputs/mapping/tempusRelease/mapping_Tempus.txt.gz
            app/build/outputs/mapping/degoogledRelease/mapping_Degoogled.txt.gz
